def playMountainKingHigh(tempo: number):
    music.set_tempo(tempo)
    music.play_tone(392, music.beat(BeatFraction.EIGHTH))
    music.play_tone(440, music.beat(BeatFraction.EIGHTH))
    music.play_tone(494, music.beat(BeatFraction.EIGHTH))
    music.play_tone(523, music.beat(BeatFraction.EIGHTH))
    music.play_tone(587, music.beat(BeatFraction.EIGHTH))
    music.play_tone(494, music.beat(BeatFraction.EIGHTH))
    music.play_tone(587, music.beat(BeatFraction.QUARTER))
    music.play_tone(554, music.beat(BeatFraction.EIGHTH))
    music.play_tone(440, music.beat(BeatFraction.EIGHTH))
    music.play_tone(554, music.beat(BeatFraction.QUARTER))
    music.play_tone(523, music.beat(BeatFraction.EIGHTH))
    music.play_tone(415, music.beat(BeatFraction.EIGHTH))
    music.play_tone(523, music.beat(BeatFraction.QUARTER))
    music.play_tone(392, music.beat(BeatFraction.EIGHTH))
    music.play_tone(440, music.beat(BeatFraction.EIGHTH))
    music.play_tone(494, music.beat(BeatFraction.EIGHTH))
    music.play_tone(523, music.beat(BeatFraction.EIGHTH))
    music.play_tone(587, music.beat(BeatFraction.EIGHTH))
    music.play_tone(494, music.beat(BeatFraction.EIGHTH))
    music.play_tone(587, music.beat(BeatFraction.EIGHTH))
    music.play_tone(784, music.beat(BeatFraction.EIGHTH))
    music.play_tone(698, music.beat(BeatFraction.EIGHTH))
    music.play_tone(587, music.beat(BeatFraction.EIGHTH))
    music.play_tone(494, music.beat(BeatFraction.EIGHTH))
    music.play_tone(587, music.beat(BeatFraction.EIGHTH))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.play_tone(0, music.beat(BeatFraction.QUARTER))
def playMountainKingLow(tempo2: number):
    music.set_tempo(tempo2)
    music.play_tone(196, music.beat(BeatFraction.EIGHTH))
    music.play_tone(220, music.beat(BeatFraction.EIGHTH))
    music.play_tone(247, music.beat(BeatFraction.EIGHTH))
    music.play_tone(262, music.beat(BeatFraction.EIGHTH))
    music.play_tone(294, music.beat(BeatFraction.EIGHTH))
    music.play_tone(247, music.beat(BeatFraction.EIGHTH))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.EIGHTH))
    music.play_tone(220, music.beat(BeatFraction.EIGHTH))
    music.play_tone(277, music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.EIGHTH))
    music.play_tone(208, music.beat(BeatFraction.EIGHTH))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.play_tone(196, music.beat(BeatFraction.EIGHTH))
    music.play_tone(220, music.beat(BeatFraction.EIGHTH))
    music.play_tone(247, music.beat(BeatFraction.EIGHTH))
    music.play_tone(262, music.beat(BeatFraction.EIGHTH))
    music.play_tone(294, music.beat(BeatFraction.EIGHTH))
    music.play_tone(247, music.beat(BeatFraction.EIGHTH))
    music.play_tone(294, music.beat(BeatFraction.EIGHTH))
    music.play_tone(392, music.beat(BeatFraction.EIGHTH))
    music.play_tone(349, music.beat(BeatFraction.EIGHTH))
    music.play_tone(294, music.beat(BeatFraction.EIGHTH))
    music.play_tone(247, music.beat(BeatFraction.EIGHTH))
    music.play_tone(294, music.beat(BeatFraction.EIGHTH))
    music.play_tone(349, music.beat(BeatFraction.QUARTER))
    music.play_tone(0, music.beat(BeatFraction.QUARTER))
music.set_volume(90)
tempo_list = [30, 40, 50, 60]
for value in tempo_list:
    playMountainKingLow(value)
    playMountainKingHigh(value)

def on_forever():
    pass
basic.forever(on_forever)
